### ISSUE TITLE
dbt-snowflake installation failing on M1 chip

### ISSUE THREAD

**Issue by PS-Arrio** [dbt-labs/homebrew-dbt#76] opened 2022-03-16 00:02 UTC
Installation keeps failing on command brew install dbt-snowflake at the following line:

/usr/local/Cellar/dbt-snowflake@1.0.0/1.0.0_2/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt-snowflakeA1.0.0--dbt-extractor-20220315-16556-1dnbhcm/dbt_extra

Error:

Last 15 lines from /Users/arriohoffman/Library/Logs/Homebrew/dbt-snowflake@1.0.0/14.pip:
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/local/Cellar/dbt-snowflake@1.0.0/1.0.0_2/libexec/bin/python3.9 /usr/local/Cellar/dbt-snowflake@1.0.0/1.0.0_2/libexec/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /private/tmp/tmpec06as9i
  cwd: /private/tmp/dbt-snowflakeA1.0.0--dbt-extractor-20220315-16556-1dnbhcm/dbt_extractor-0.4.0
  Preparing metadata (pyproject.toml): finished with status 'error'
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by DavidErickson7** [comment] 2022-03-16 18:24
- Intel macbook pro
- macOS Monterey 12.3 (latest version)

```
Last 15 lines from /Users/home/Library/Logs/Homebrew/dbt-snowflake/14.pip:
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/local/Cellar/dbt-snowflake/1.0.0_2/libexec/bin/python3.9 /usr/local/Cellar/dbt-snowflake/1.0.0_2/libexec/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /private/tmp/tmpq4yu3j5c
  cwd: /private/tmp/dbt-snowflake--dbt-extractor-20220316-92295-1wsma56/dbt_extractor-0.4.0
  Preparing metadata (pyproject.toml): finished with status 'error'
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/dbt-labs/homebrew-dbt/issues

These open issues may also help:
dbt-snowflake installation failing on M1 chip https://github.com/dbt-labs/homebrew-dbt/issues/76
Issue Installing dbt-snowflake on Mac https://github.com/dbt-labs/homebrew-dbt/issues/67
home@Davids-MBP-2 ~ %
```

**Comment by mz-packhelp** [comment] 2022-03-16 18:30
Same thing for me

**Comment by thejacket** [comment] 2022-03-16 18:34
Same thing for me on Intel chip, MBP 2020, macOS Monterey 12.3
```

==> Installing dbt from dbt-labs/dbt
==> Installing dependencies for dbt-labs/dbt/dbt: libffi, tcl-tk and python@3.8
==> Installing dbt-labs/dbt/dbt dependency: libffi
==> Pouring libffi--3.4.2.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/libffi/3.4.2: 17 files, 599.7KB
==> Installing dbt-labs/dbt/dbt dependency: tcl-tk
==> Pouring tcl-tk--8.6.12_1.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/tcl-tk/8.6.12_1: 3,045 files, 51.8MB
==> Installing dbt-labs/dbt/dbt dependency: python@3.8
==> Pouring python@3.8--3.8.12_1.monterey.bottle.tar.gz
==> /usr/local/Cellar/python@3.8/3.8.12_1/bin/python3 -s setup.py --no-user-cfg 
==> /usr/local/Cellar/python@3.8/3.8.12_1/bin/python3 -s setup.py --no-user-cfg 
==> /usr/local/Cellar/python@3.8/3.8.12_1/bin/python3 -s setup.py --no-user-cfg 
🍺  /usr/local/Cellar/python@3.8/3.8.12_1: 4,451 files, 71.8MB
==> Installing dbt-labs/dbt/dbt
==> python3 -m venv --system-site-packages /usr/local/Cellar/dbt/0.21.1_1/libexe
==> /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/pip install --upgrade pip
==> /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/pip install -v --no-deps --no-bin
==> /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/pip install -v --no-deps --no-bin
==> /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/pip install -v --no-deps --no-bin
==> /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/pip install -v --no-deps --no-bin
==> /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/pip install -v --no-deps --no-bin
==> /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/pip install -v --no-deps --no-bin
==> /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/pip install -v --no-deps --no-bin
==> /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/pip install -v --no-deps --no-bin
==> /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/pip install -v --no-deps --no-bin
==> /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/pip install -v --no-deps --no-bin
==> /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/pip install -v --no-deps --no-bin
==> /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/pip install -v --no-deps --no-bin
==> /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/pip install -v --no-deps --no-bin
==> /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/pip install -v --no-deps --no-bin
==> /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/pip install -v --no-deps --no-bin
==> /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/pip install -v --no-deps --no-bin
==> /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/pip install -v --no-deps --no-bin
==> /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/pip install -v --no-deps --no-bin
==> /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/pip install -v --no-deps --no-bin
==> /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/pip install -v --no-deps --no-bin
==> /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/pip install -v --no-deps --no-bin
==> /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/pip install -v --no-deps --no-bin
Last 15 lines from /Users/ph-mariusz/Library/Logs/Homebrew/dbt/24.pip:
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/python3 /usr/local/Cellar/dbt/0.21.1_1/libexec/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /private/tmp/tmpg_27rfm6
  cwd: /private/tmp/dbt--dbt-extractor-20220316-40753-545mv5/dbt_extractor-0.4.0
  Preparing metadata (pyproject.toml): finished with status 'error'
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by paultroy** [comment] 2022-03-16 21:20
Same error for me. MBP, M1. Receiving same error when attempting install using Rosetta or arm64.

**Comment by CloudChaoszero** [comment] 2022-03-16 23:45
Same

**Comment by MortenDHansen** [comment] 2022-03-17 11:31
Not related to the M1 chip. I have same issue on Intel i9 mac with big sur.

**Comment by nathaniel-may** [comment] 2022-03-17 16:24
Hi everyone! Thanks for raising this and posting your output. I've been able to recreate this locally and we are looking into it.

**Comment by nathaniel-may** [comment] 2022-03-17 18:04
Hey, folks! We've identified the issue and have a resolution. For the latest please follow [this core ticket](https://github.com/dbt-labs/dbt-core/issues/4891) which I will be updating as we get more information.

**Comment by bbakiu** [comment] 2022-03-18 09:02
Hey @nathaniel-may,

Can you please tell us when do you plan to release 1.0.4? It would be extremely helpful.

Thank you!

**Comment by nathaniel-may** [comment] 2022-03-18 15:41
For everyone having issues installing brew, you should be able to get this to work now by uninstalling and reinstalling which will pull down the updated formula with the new patch of core. We're working on a solution that doesn't require uninstalling, but I wanted you to have this sooner.

```
brew update
brew uninstall dbt-snowflake
brew install dbt-snowflake
```

If you see the following line in the brew output, it verifies you'll have the new version of core that builds correctly.
```
==> Downloading https://...url.../dbt-core-1.0.4.tar.gz
```

**Comment by PS-Arrio** [comment] 2022-03-18 20:13
While the extractor issue looks to be resolved, I'm still experiencing an error:

Last 15 lines from /Users/arriohoffman/Library/Logs/Homebrew/dbt-snowflake/08.pip:
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"
  
  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'/private/tmp/dbt-snowflake--cffi-20220318-6744-13qkt2q/cffi-1.15.0/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' install --record /private/tmp/pip-record-j_jq6e7u/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Homebrew/Cellar/dbt-snowflake/1.0.0_3/libexec/include/site/python3.9/cffi
  cwd: /private/tmp/dbt-snowflake--cffi-20220318-6744-13qkt2q/cffi-1.15.0/
  Running setup.py install for cffi: finished with status 'error'
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> cffi

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by thejacket** [comment] 2022-03-19 13:33
> For everyone having issues installing with brew, you should be able to get this to work now by uninstalling and reinstalling which will pull down the updated formula with the new patch of core. We're working on a solution that doesn't require uninstalling, but I wanted you to have this sooner.
> 
> ```
> brew update
> brew uninstall dbt-snowflake
> brew install dbt-snowflake
> ```
> 
> If you see the following line in the brew output, it verifies you'll have the new version of core that builds correctly.
> 
> ```
> ==> Downloading https://...url.../dbt-core-1.0.4.tar.gz
> ```

`brew install dbt` still uses 0.21.1_1

`brew install dbt-bigquery` uses 1.0.3

**Comment by nathaniel-may** [comment] 2022-03-21 17:14
@PS-Arrio, sorry to hear you're still having issues. It looks like this is a separate error than the one you originally posted. If you are still having this issue could you open another ticket and tag me? I'm going to close this one out since the original issue has been addressed.

**Comment by nathaniel-may** [comment] 2022-03-21 17:16
Hi @thejacket,

Thanks for your comment. I'm working on verifying with dbt-bigquery specifically, but here is what I think is happening:

Since 1.0.0, we changed the install package from `dbt` to `dbt-<adapter>` which is why `brew install dbt` installs an old version. Following our [documentation](https://docs.getdbt.com/dbt-cli/install/homebrew) `brew install dbt-bigquery` is the correct way to install dbt with homebrew.

If you run `dbt --version` after installing you should see the core version is 1.0.4 while the bigquery adapter version is 1.0.0 but both are the latest available, which is the expected behavior.

**Closed** 2022-03-21 17:17 UTC

**Comment by spcvalente** [comment] 2022-06-08 13:31
same as @nathaniel-may, I was wrongly trying to install *dbt* (old version) and not dbt-_adapter_ ,be it snowflake, bigquery, etc
